### ISSUE TITLE
Is there anyway you could make it easier to edit the system prompt directly?

### ISSUE THREAD

**Issue by lameTookan** [hc20k/LLMChat#1]
Like if I just wanted to edit the system prompt directly? I have been looking for a bot  that allows me to choose what system prompt is included with every request

I understand that you've included a lot of options to edit stuff surrounding that but is there just a file I can edit to edit it directly?

**Comment by hc20k** [comment]
This is a great idea, I'll implement this in the next commit :)

**Comment by hc20k** [comment]
Feature added, make sure to set the `Bot.initial_prompt` value in your config file.

**Comment by lameTookan** [comment]
Is this just the initial prompt in the chat or is it the actual system prompt? Like I'm trying to build a dungeon master  bot and I have a fairly long prompt with a ton of commands for use in a small server with a couple of friends. 

As the game goes on if GPT forgets (or its trimmed from the request) the game becomes unplayable. The prompt specifies that the ai recount important events and the current state of the game in each message so loosing the previous chats doesn't matter so much.  

I realize it would be far better just to put commands within code but my skills there are fairly limited right now and besides I want this to be something I can change over time with different games and prompts.

**Comment by hc20k** [comment]
It's an actual system prompt always inserted at the beginning of the transcript using the system role in OpenAI's API. I find that the model usually does forget that prompt, which is why I implemented `reminder` which seems to work a lot better.
